on: [push, pull_request]

name: Build wasm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Get emscripten
      uses: mymindstorm/setup-emsdk@v9

    - name: Cache the build directory
      uses: actions/cache@v2
      with:
        path: build
        key: build

    - name: Configure the build
      run: emcmake cmake -S . -B build

    - name: Run the build
      run: |
        cd build
        emmake make

    - name: Publish binaries
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        allowUpdates: true
        removeArtifacts: true
        artifacts: "build/scran.js,build/scran.wasm"
        name: latest
        tag: latest
        body: "Wasm binary for standard web deployments."
