on: [push, pull_request]

name: Build wasm & Publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup node for npm
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Get emscripten
      uses: mymindstorm/setup-emsdk@v9

    - name: Test node version
      run: | 
        node -v
        npm -v

    - name: Install deps
      run: npm i --include=dev

    # - name: Generate node build and run test
    #   run: |
    #     bash build.sh main
    #     NODE_OPTIONS='--experimental-vm-modules --experimental-wasm-threads --experimental-wasm-bulk-memory' npx jest

    - name: Generate wasm module build
      run: bash build.sh module

    - name: Parcellize build
      run: |
        npm i --include=dev
        npm run build

    - name: Setup node for npm
      uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup node for gpr
      uses: actions/setup-node@v2
      with:
        registry-url: https://npm.pkg.github.com/

    - name: Publish to Github package registry
      run: |
        mv package.gpr.json package.json
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}