on: [push, pull_request]

name: Build wasm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [web, node]

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Get emscripten
      uses: mymindstorm/setup-emsdk@v9

    - name: Configure the build for web
      if: matrix.mode == 'web'
      run: emcmake cmake -S . -B build

    - name: Configure the build for Node.js
      if: matrix.mode == 'node'
      run: emcmake cmake -S . -B build -D COMPILE_NODE=ON

    - name: Run the build
      run: |
        cd build
        emmake make

    - name: Publish library for web
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master' && matrix.mode == 'web' 
      with:
        allowUpdates: true
        removeArtifacts: true
        artifactErrorsFailBuild: true
        artifacts: "build/scran.js,build/scran.wasm,build/scran.worker.js"
        name: latest-web
        tag: latest-web
        body: "JS library for web deployments."

    - name: Publish library for Node.js
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master' && matrix.mode == 'node' 
      with:
        allowUpdates: true
        removeArtifacts: true
        artifactErrorsFailBuild: true
        artifacts: "build/scran.js,build/scran.wasm,build/scran.worker.js"
        name: latest-node
        tag: latest-node
        body: "JS library for Node.js deployments."

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Publish to Github package registry
      run: |
        npm ci
        bash build.sh main
        bash build.sh module
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}