on: [push, pull_request]

name: Build wasm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [standard, node]

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Get emscripten
      uses: mymindstorm/setup-emsdk@v9

    - name: Cache the build directory
      uses: actions/cache@v2
      with:
        path: build
        key: build-${{ matrix.mode }}

    - name: Configure the build
      if: matrix.mode == 'standard'
      run: emcmake cmake -S . -B build

    - name: Configure the build
      if: matrix.mode == 'node'
      run: emcmake cmake -S . -B build -D COMPILE_NODE=ON

    - name: Run the build
      run: |
        cd build
        emmake make

    - name: Publish binaries
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master' && (matrix.mode == 'standard' || matrix.mode == 'node')
      with:
        allowUpdates: true
        removeArtifacts: true
        artifacts: "build/scran.js,build/scran.wasm"
        name: latest-${{ matrix.mode }}
        tag: latest-${{ matrix.mode }}
        body: format("Wasm binary (`{0}`).", ${{ matrix.mode }}) 
