on: [push, pull_request]

name: Build wasm & Publish

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [web, node]

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Get emscripten
      uses: mymindstorm/setup-emsdk@v9

    - name: Generate wasm build
      run: |
        npm i --include=dev
        bash build.sh module

    - name: Test builds
      run: npm run test

    - name: Parcellize build
      run: npm run build

    - name: Setup node for npm
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup node for gpr
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Publish to Github package registry
      run: |
        mv package.gpr.json package.json
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}