on:
  push:
    branches:
      - master

      
name: Build documentation

jobs:
  doxygenator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add Pretty CSS
      uses: wei/wget@v1
      with:
        args: -O docs/doxygen-awesome.css https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: docs/

    - name: Set up Node
      uses: actions/setup-node@v2

    - name: Restore the node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Install JSDoc
      run: npm i --include-dev

    - name: Run JSDoc
      run: npm run jsdoc

    - name: Organize files
      run: sudo mv docs/html docs/built/wasm

    - name: GH Pages Deployment
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/built
        target-folder: docs
        clean: true # Automatically remove deleted files from the deploy branch
