name: Node.js Package

# TODO: uncomment before merging with master
# on:
#   release:
#     types: [created]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 12
  #     - run: npm ci
  #     - run: bash build.sh main
  #     - run: bash build.sh module
  #     - run: npm test

  publish-gpr:
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: bash build.sh main
      - run: bash build.sh module
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}