on:
  workflow_run:
    workflows: [Test JS bindings]
    types: [completed]
    branches: [master]

name: Build and publish to NPM 

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: ghcr.io/jkanche/scran.js/builder:latest
    defaults:
      run:
        working-directory: /scran.js

    steps:
    - name: Get to the right branch
      run: |
        git fetch --all
        git checkout $GITHUB_SHA

    - name: Update node build 
      run: bash build.sh main

    - name: Update module build
      run: bash build.sh module

    - name: Update NPM packages
      run: npm i --include=dev

    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to NPM
      run: npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
